CREATE TABLE items (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
	date DATETIME,
	priority SMALLINT UNSIGNED,
	completed TINYINT,
    PRIMARY KEY (id)
 );